set(CHIPLETS_QEMU_NAME qemu-x64-minimal)
set(CHIPLETS_QEMU_INSTALL_NAME qemu-x64-minimal)
set(CHIPLETS_QEMU_SOURCE_COPY_NAME qemu-src-x64-minimal)
set(CHIPLETS_QEMU_BUILD_NAME qemu-x64-minimal)

set(CHIPLETS_QEMU_SOFTMMU_TARGET x86_64-softmmu)
set(CHIPLETS_QEMU_DEVICE_CONFIG_TARGET x86_64)
set(CHIPLETS_QEMU_DEVICE_CONFIG microvm-minimal)
set(CHIPLETS_QEMU_SYSTEM_BINARY qemu-system-x86_64)
