ram_access = "qemu-mediated"

[[devices]]
name = "blk0"
type = "virtio-blk"
mmio = { base = "0xfeb00000", size = "0x200", irq = 48 }

[[devices]]
name = "con0"
type = "virtio-console"
mmio = { base = "0xfeb00200", size = "0x200", irq = 49 }

[targets.qemu]
type = "virt"
binary = "build/out/qemu/bin/qemu-system-aarch64"
parameters = { memory = "512M", kvm = false, pcie = false, cpu = "max" }

[[targets.qemu.devices]]
name = "blk0"
socket = "run/axi-a64.sock"
log = "run/axi-a64-backend.log"
image = "run/blk0.img"
readonly = false

[[targets.qemu.devices]]
name = "con0"
socket = "run/axi-console-a64.sock"
log = "run/axi-console-a64-backend.log"
output = "run/cond-a64.out"
