[machine]
type = "microvm"
memory = "512M"
kvm = true
pcie = false

[qemu]
binary = "out/qemu-x64-minimal/bin/qemu-system-x86_64"
bios_dir = "build/qemu-pc-bios"

[transport]
ram_access = "qemu-mediated"

[[mmio_windows]]
name = "blk0"
base = "0xfeb00000"
size = "0x200"
irq = 16
socket = "run/axi-bus.sock"
target = "blk0"
enabled = true
